### ISSUE TITLE
Update semver dep

### ISSUE THREAD

**Issue by phated** [gulpjs/semver-greatest-satisfied-range#7]

**Comment by romellem** [comment]
Hi, is this just as simple as updating the version within the **package.json** file? If so, I made a PR for that (#9). Tests seem to run the same as they did with semver at v4.

If I'm missing something, feel free to disregard this.

Thanks again for all your hard work on gulp and its dependencies! ❤️

**Comment by phated** [comment]
This is being removed for https://github.com/phated/sver-compat
